_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '../yolov5/_base_/yolov5_cspresnet.yml',
  '../yolov5/_base_/yolov5_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 5
weights: output/yolov5_convnext_s_300e_coco/model_final
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/convnext_tiny_22k_224.pdparams


YOLOv5:
  backbone: ConvNeXt
  neck: YOLOCSPPAN
  yolo_head: YOLOv5Head
  post_process: ~

ConvNeXt:
  arch: 'tiny'
  drop_path_rate: 0.4
  layer_scale_init_value: 1.0
  return_idx: [1, 2, 3]


TrainReader:
  batch_size: 8


epoch: 36
LearningRate:
  base_lr: 0.0002
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [36]
    use_warmup: false

OptimizerBuilder:
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0005
