_BASE_: [
  'yolov5_cspdarknet.yml',
]

CSPDarkNet:
  arch: "P6"
  return_idx: [2, 3, 4, 5]

YOLOv5Head:
  anchors: [[19, 27], [44, 40], [38, 94],
            [96, 68], [86, 152], [180, 137],
            [140, 301], [303, 264], [238, 542],
            [436, 615], [739, 380], [925, 792]]
  anchor_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]]
  stride: [8, 16, 32, 64]

YOLOv5Loss:
  downsample_ratios: [8, 16, 32, 64]
  balance: [4.0, 1.0, 0.25, 0.06]
  box_weight: 0.05
  obj_weight: 0.7
  cls_weght: 0.3
