_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_p6.yml',
  '_base_/yolov7p6_elannet.yml',
  '_base_/yolov7p6_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7p6_e6_300e_coco/model_final

arch: E6
use_aux: True


TrainReader:
  batch_size: 10
