_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_high.yml',
  '_base_/yolov5p6_cspdarknet.yml',
  '_base_/yolov5p6_reader.yml',
]
depth_mult: 1.33
width_mult: 1.25

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5p6_x_300e_coco/model_final


TrainReader:
  batch_size: 8 # default 8 gpus, total bs = 64
